# This workflow will build a Java project with Maven
name: Java CI with Maven in Linux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      workdir: myproject-ci
    strategy:
      matrix:
        # test against several Java versions:
        include:
          - java: 8
            additional-maven-args: > 
              -Pjacoco 
              -DrepoToken=$COVERALLS_REPO_TOKEN
              -DpullRequest=${{ github.event.pull_request.number }} 
              coveralls:report
          - java: 11
    name: Build with Java ${{ matrix.java }} on Linux
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
       java-version: ${{ matrix.java }}
    - name: Cache maven packages
      uses: actions/cache@v2
      with:
       path: ~/.m2
       key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
       restore-keys: ${{ runner.os }}-m2-
    - name: Build with Maven
      # removed clean because in workflow is useless
      # removed '-f myproject-ci/pom.xml' when 'working_directory' is set 
      run: >
        mvn verify ${{ matrix.additional-maven-args }}
      working-directory: ${{ env.workdir }}
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
    - name: Generate JUnit Report
      run: >
        mvn surefire-report:report-only site:site -DgenerateReports=false
      working-directory: ${{ env.workdir }}
      # function always() always return true. In this way, the maven build terminates also if it failed.
      if: ${{ always() }}
    - name: Archive Junit Report
      # actions/upload-artifact@v2 is deprecated version 
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
       name: Surefire-report-with-jdk-${{ matrix.java }}
       path: '**/target/site'
    - name: Archive Jacoco directory
      uses: actions/upload-artifact@v4
      if: ${{ matrix.additional-maven-args == '-Pjacoco' }}
      with:
       name: Jacoco-report-with-jdk-${{ matrix.java }}
       path: '**/target/site/jacoco'
